### ISSUE TITLE
Use @pika/pack

### ISSUE THREAD

**Issue by ABuffSeagull** [staghouse/js-essentials#17]
https://www.pika.dev/blog/introducing-pika-pack/
:smirk:

**Comment by staghouse** [comment]
Whats the purpose - another tool to pack up the files for when we publish?

**Comment by ABuffSeagull** [comment]
Did you even read it :smirk: :smirk: :smirk:

**Comment by staghouse** [comment]
I know what it is - I was just asking what YOUR thoughts were on the implementation vs others 😏

**Comment by ABuffSeagull** [comment]
In all seriousness, ES Modules has been in browsers for a while now, and it's VERY close to being out of experimental, so everyone should be switching to them, and pika makes the transition very painless.
Plus all the other goodies.
As per why I like it over others, is that minus the tiny bit of config in the package.json, it's got very sane defaults, and it's stupid easy to use.

**Comment by staghouse** [comment]
As we discovered - it was not working as expected
